# Use root/example as user/password credentials
# version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - ./mongodb_data:/data/db
            - ./configdb:/data/configdb

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMIN_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMIN_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ADMIN_USERNAME}:${MONGODB_ADMIN_PASSWORD}@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo
